# Config file for analyser

title = "Analyser config"

[owner]
name = "Baran Nama"
dob = 2019-01-09T15:55:00-08:00

[log]
# whether log method name
is_method_name = false

[output]
features = "Name,Pistol_Rounds_Won_Percentage,HS_Percentage,Clutches_Won,ADR,FPR,FKR,APR,K_D_Diff_Round,Flash_Assists_Round,Blind_Players_Killed_Round,Blind_Kills,Grenade_Damage_Round,Fire_Damage_Round,Time_Flashing_Opponents_Round,Accuracy,Num_Times_Trader,Num_Times_Tradee,KAST,MVP,Won"
analyzer_version = "0.2.4"
round_print = true
mapnameAlias = { cobblestone = "cbble" }

[test]
demofile_path = "/home/baran/Desktop/demo_files/working_demos"
log_prefix = "log"
output_prefix = "stat"
concurrent_worker = 1
stdout = false

# variables related to analyser
[algorithm]
# default money for round start
roundStartMoney = 800
# num. of seconds after a firt kill killer have to be alive to count as first kill
after_first_kill = 2
# minimum seconds of killing an attacker will count as saving
before_save_seconds = 3
# max health of hurted player count as saved
max_health_saved = 30
# seconds to check croshair replecament just before a kill
before_crashair = 0.3
